config/routes.rb
Rails.application.routes.draw do



  get '/all', to: 'all#index'

  get '/comingsoon', to: 'soon#index'

  root :to => 'stories#index'

  resources :videos
  resources :articles do
    member do
      put :publish
    end
  end
  get '/profile/:id' , to: 'stories#profile'

  get '/category/:id' , to: 'categories#show', as: 'category'

  get '/story/new', to: 'choose#index'

  get '/stories', to: 'stories#index'


  resources :videos do
    resources :comments
    member do
      put "like", to: "videos#upvote"
      put "unlike", to: "videos#downvote"
    end
  end



  devise_for :users
  resources :stories do
    member do
      put :publish
    end
    resources :messages do
      member do
        put :is_correct
        put :is_correct2
      end
    end
  end


  get 'stories/:id/view', to: 'stories#view'
end

app/views/navs/_video_side_bar.html.erb
<style>
  .homepage-navbar-side-navigation-anchor-items{
    color:white !important;
    transform:translateY(20px);
  }
    .pods-link{
      color:black !important;
    }
</style>
<div class = "video-side-bar">
  <div style = "animation-delay: 50ms;" class = "homepage-navbar-side-navigation-list-item-container first-item animated pulse">
    <img class = "homepage-navbar-side-navigation-list-item-logo" src = "http://www.freeiconspng.com/uploads/upload-icon-31.png">
    <% if user_signed_in? %>
      <%= link_to 'Publish a video', new_video_path, remote:true, class:'video-click homepage-navbar-side-navigation-anchor-items ' %>
    <% else %>
        <%= link_to 'Publish a video', 'users/sign_in',  class:'video-click homepage-navbar-side-navigation-anchor-items ' %>
    <% end %>
    </div>
  <div style = "animation-delay: 50ms;" class = "homepage-navbar-side-navigation-list-item-container first-item animated pulse">
    <img class = "homepage-navbar-side-navigation-list-item-logo" src = "http://prihatin.kpkt.gov.my/assets/img/flat03.png">
    <a href = "../../../../../Desktop/StoryTime/app/views/videos/new" class = "homepage-navbar-side-navigation-anchor-items ">Set up a series</a>
  </div>
  <hr style = "border-color:grey;">
  <div style = "animation-delay: 50ms;" class = "homepage-navbar-side-navigation-list-item-container first-item animated pulse">
    <img class = "homepage-navbar-side-navigation-list-item-logo" src = "https://cdn.iconscout.com/public/images/icon/free/png-512/fireworks-sparkler-sparkles-star-celebration-diwali-atashbaji-emoj-symbol-34758a03e24fda02-512x512.png">
    <a href = "../../../../../Desktop/StoryTime/app/views/videos/new" class = "homepage-navbar-side-navigation-anchor-items">All video series</a>
  </div>
  <div style = "animation-delay: 50ms;" class = "homepage-navbar-side-navigation-list-item-container first-item animated pulse">
    <img class = "homepage-navbar-side-navigation-list-item-logo" src = "http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/favorite-star-icon.png">
    <a href = "../../../../../Desktop/StoryTime/app/views/videos/new" class = "homepage-navbar-side-navigation-anchor-items ">Popular videos</a>
  </div>
  <div style = "animation-delay: 50ms;" class = "homepage-navbar-side-navigation-list-item-container first-item animated pulse">
    <%= image_tag 'love_icon.png', class:'homepage-navbar-side-navigation-list-item-logo' %>
    <a href = "../../../../../Desktop/StoryTime/app/views/videos/new" class = "homepage-navbar-side-navigation-anchor-items">Hearted videos</a>
  </div>
  <div style = "animation-delay: 50ms;" class = "homepage-navbar-side-navigation-list-item-container first-item animated pulse">
    <%= image_tag 'badge-flat.png', class:'homepage-navbar-side-navigation-list-item-logo' %>
    <a href = "../../../../../Desktop/StoryTime/app/views/videos/new" class = "homepage-navbar-side-navigation-anchor-items">Featured videos</a>
  </div>
</div>


<script>
</script>

app/views/navs/_videos_top_nav.html.erb
<nav  class="navbar navbar-default video-navbar navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a style = "margin-top:-6px;" class = "videos-brand" href="../../../../../Desktop/StoryTime/app/views/videos">Chalkboard </a></li>

      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <i class="fa fa-search videos-search-icon" aria-hidden="true"></i>
          <input class = "videos-search" type="text" class="form-control" placeholder="Search">
        </div>
      </form>
      <ul  class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li  class = "homepage-navbar-explore-information-object">
        <% else %>
            <li style = "transform:translateX(-20px);" class = "homepage-navbar-explore-information-object">
        <% end %>
        <div style = "transform:translate(-40px,-10px);" class="dropdown">
          <i style = "cursor:pointer;font-size:28px;" class="fa fa-caret-square-o-down dropdown-toggle homepage-navbar-fa-grcode animated rubberBand" data-toggle="dropdown"></i>

          <span class="caret"></span>
          <ul class="dropdown-menu homepage-navbar-dropdown-menu">
            <li class = "text-center"><span class = "homepage-navbar-explore-text-element">Explore</span></li>
            <li>
              <div class = "dropdown-left">
                <div class = "homepage-navbar-explore-content-container">
                  <div class="row content homepage-navbar-row-content">
                    <a href = "../articles"><div class="col-md-4 col-sm-6">
                      <%= image_tag 'book-flat.png', class:'nav-image' %>
                      <p class = "homepage-navbar-icon-text">Articles</p>
                    </div></a>
                    <a href = "../podcasts"><div class="col-md-4 col-sm-6">
                      <img class = "nav-image" src = "http://icons.iconarchive.com/icons/dtafalonso/yosemite-flat/512/Music-icon.png">
                      <p class = "homepage-navbar-icon-text">Podcast</p>
                    </div></a>
                    <a href = "../../../../../Desktop/StoryTime/app/views/videos"><div  class="col-md-4 col-sm-6">
                      <img class = "nav-image" src = "https://cdn3.iconfinder.com/data/icons/complete-set-icons/512/video512x512.png">
                      <p class = "homepage-navbar-icon-text">Videos</p>
                    </div></a>
                    <div class = "col-md-4 col-sm-6 homepage-navbar-explore-row-1">
                      <%= link_to (image_tag 'https://media.freepik.com/accounts/img/badges/favorites_gold.svg', class:'nav-image', style: 'margin-left:10px;'), '../meets'%>
                      <p class = "homepage-navbar-icon-text">MeetUp</p>
                    </div>
                    <div class = "col-md-4 col-sm-6 homepage-navbar-explore-row-1">
                      <img class = "nav-image" src = "https://cdn4.iconfinder.com/data/icons/flat-icon-set/2125/flat_icons-graficheria.it-11.png">
                      <p class = "homepage-navbar-icon-text text-center homepage-navbar-docs-text">Docs</p>
                    </div>
                    <div class = "col-md-4 col-sm-6 homepage-navbar-explore-row-1">
                      <img class = "nav-image" src = "https://cdn0.iconfinder.com/data/icons/flat-designed-circle-icon/1000/camera.png">
                      <p class = "homepage-navbar-icon-text">Pictures</p>
                    </div>
                    <div class = "col-md-4 col-sm-6 homepage-navbar-explore-row-2-exception">
                      <%= link_to (image_tag 'people.png', class:'nav-image'), '../members'%>
                      <p class = "homepage-navbar-icon-text">People</p>
                    </div>
                    <div class = "col-md-4 col-sm-6 homepage-navbar-explore-row-1">
                      <p class = "homepage-navbar-icon-text">Group Chat</p>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        </div>
        </li>

        <% if user_signed_in? %>
        <li style = "transform:translateX(-20px); class="dropdown">
        <div class=" dropdown-toggle" type="button" data-toggle="dropdown"><%= avatar_for(current_user,size:100) %></div>
        <ul style = "width:400px;" class="dropdown-menu">

          <% if current_user.image? %>
              <div style = "margin-top:-5px !important; width:100%;height:200px;background:url(<%= current_user.image.url(:large) %>) center center;background-size: cover;">
          <% else %>
              <div style = "margin-top:-5px !important; width:100%;height:auto;"><h1 style = "margin-top:10%;font-size:50px;font-weight:bold;" class = "text-center"><%= current_user.firstname[0] + " "  + current_user.lastname[0]%></h1>
          <% end %>
          </div>
          <h1 style = "color:black !important;" class = "text-center"><%= current_user.firstname + " "  + current_user.lastname %></h1>
          <li><a href="../teachers/<%= current_user.username %>">Profile</a></li>
          <li><a href="#">Edit Profile</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Sign Out</a></li>
        </ul>
        </li>
            <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>