config/routes.rb
Rails.application.routes.draw do



  get '/all', to: 'all#index'

  get '/comingsoon', to: 'soon#index'

  root :to => 'stories#index'

  resources :videos
  resources :articles do
    member do
      put :publish
    end
  end
  get '/profile/:id' , to: 'stories#profile'

  get '/category/:id' , to: 'categories#show', as: 'category'

  get '/story/new', to: 'choose#index'

  get '/stories', to: 'stories#index'


  resources :videos do
    resources :comments
    member do
      put "like", to: "videos#upvote"
      put "unlike", to: "videos#downvote"
    end
  end



  devise_for :users
  resources :stories do
    member do
      put :publish
    end
    resources :messages do
      member do
        put :is_correct
        put :is_correct2
      end
    end
  end


  get 'stories/:id/view', to: 'stories#view'
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :messages
  belongs_to :category

  is_impressionable counter_cache: true,  :unique => :all




  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", large: "2000x2000>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/



  has_attached_file :cover, styles: { medium: "500x500>", large: "2000x2000>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/


  has_attached_file :video,
                    :styles => {:thumb => ["400x400#", :jpg]}
  validates_attachment_content_type :video, content_type: /\Avideo/


  validates :title, presence: true
  validates :synopsis, presence: true
  validates :texter, presence: true
  validates :reciever, presence: true




end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :view, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.order(impressions_count: :desc).paginate(:page => params[:page], :per_page => 21)
    @first = @stories.first
    @user = current_user
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @messages = @story.messages.order(created_at: :desc).reverse

  end



  def publish
    @story = Story.find(params[:id])
    @story.ispublished = true
    @story.save
  end


  # GET /stories/new
  def new
    @story = Story.new
    @category = Category.new
  end

  # GET /stories/1/edit
  def edit

  end


  def profile
    @user = User.find_by_id(params[:id])


    if User.find_by_id(params[:id])
      @email = params[:id]
      @user = User.find_by_id(params[:id])
      @views = 1
      @user.stories.each do |i|
        @views += i.impressionist_count(:filter => :params)
      end
      @user.articles.each do |i|
        @views += i.impressionist_count(:filter => :params)
      end

    else
      redirect_to "/"
    end

  end

  # POST /stories
  # POST /stories.json
  def create
    @story = current_user.stories.build (story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Item was successfully created.' }
        format.json { render json: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view
    @messages = @story.messages.order(created_at: :desc).reverse
    @count = Story.count
    if @story.ispublished
      impressionist(@story)
      @randomStory = Story.order("RANDOM()").first
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :category_id, :synopsis,:texter,:reciever, :image, :video, :cover)
    end


end

app/helpers/stories_helper.rb
module StoriesHelper

end

app/views/stories/_form.html.erb
<style>
  button[type="submit"]{
    color:black;
    background:rgb(240,240,255);
  }

   *, *:before, *:after {
     box-sizing: border-box;
     margin: 0;
     padding: 0;
   }

  body {
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
    background: rgb(21,21,21);
  }

  input, button {
    border: none;
    outline: none;
    background: none;
    font-family: 'Open Sans', Helvetica, Arial, sans-serif;
  }

  .tip {
    font-size: 20px;
    margin: 40px auto 50px;
    text-align: center;
  }

  .cont {
    overflow: hidden;
    position: relative;
    width: 900px;
    height: 550px;
    margin: 0 auto 100px;
    background: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://i.pinimg.com/736x/23/e2/f2/23e2f2717ce8e472a676f6e08fee221c.jpg) center center no-repeat;
    background-size:cover;
    color:white !important;

  }

  .form {
    position: relative;
    width: 640px;
    height: 100%;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
    padding: 50px 30px 0;
  }
  label, input {
    color:white !important;
  }

  .sub-cont {
    overflow: hidden;
    position: absolute;
    left: 640px;
    top: 0;
    width: 900px;
    height: 100%;
    padding-left: 260px;
  }
  .cont.s--signup .sub-cont {
    -webkit-transform: translate3d(-640px, 0, 0);
    transform: translate3d(-640px, 0, 0);
  }

  button {
    display: block;
    margin: 0 auto;
    width: 260px;
    height: 36px;
    border-radius: 30px;
    color: #fff;
    font-size: 15px;
    cursor: pointer;
  }

  .img {
    overflow: hidden;
    z-index: 2;
    position: absolute;
    left: 0;
    top: 0;
    width: 260px;
    height: 100%;
    padding-top: 360px;
  }
  .img:before {
    content: '';
    position: absolute;
    right: 0;
    top: 0;
    width: 900px;
    height: 100%;
    background-image: url("../assets/log.png");
    background-size: cover;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
  }
  .img:after {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.6);
  }
  .cont.s--signup .img:before {
    -webkit-transform: translate3d(640px, 0, 0);
    transform: translate3d(640px, 0, 0);
  }
  .img__text {
    z-index: 2;
    position: absolute;
    left: 0;
    top: 50px;
    width: 100%;
    padding: 0 20px;
    text-align: center;
    color: #fff;
    -webkit-transition: -webkit-transform 1.2s ease-in-out;
    transition: -webkit-transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out;
    transition: transform 1.2s ease-in-out, -webkit-transform 1.2s ease-in-out;
  }
  .img__text h2 {
    margin-bottom: 10px;
    font-weight: normal;
  }
  .img__text p {
    font-size: 14px;
    line-height: 1.5;
  }
  .cont.s--signup .img__text.m--up {
    -webkit-transform: translateX(520px);
    transform: translateX(520px);
  }
  .img__text.m--in {
    -webkit-transform: translateX(-520px);
    transform: translateX(-520px);
  }
  .cont.s--signup .img__text.m--in {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  .img__btn {
    overflow: hidden;
    z-index: 2;
    position: relative;
    width: 100px;
    height: 36px;
    margin: 0 auto;
    background: transparent;
    color: #fff;
    text-transform: uppercase;
    font-size: 15px;
    cursor: pointer;
  }
  .img__btn:after {
    content: '';
    z-index: 2;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    border: 2px solid #fff;
    border-radius: 30px;
  }
  .img__btn span {
    position: absolute;
    left: 0;
    top: 0;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    width: 100%;
    height: 100%;
    -webkit-transition: -webkit-transform 1.2s;
    transition: -webkit-transform 1.2s;
    transition: transform 1.2s;
    transition: transform 1.2s, -webkit-transform 1.2s;
  }
  .img__btn span.m--in {
    -webkit-transform: translateY(-72px);
    transform: translateY(-72px);
  }
  .cont.s--signup .img__btn span.m--in {
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }
  .cont.s--signup .img__btn span.m--up {
    -webkit-transform: translateY(72px);
    transform: translateY(72px);
  }

  h2 {
    width: 100%;
    font-size: 26px;
    text-align: center;
  }

  label {
    display: block;
    width: 260px;
    margin: 25px auto 0;
    text-align: center;
  }
  label span {
    font-size: 12px;
    color: black;
    text-transform: uppercase;
  }

  input {
    display: block;
    width: 100%;
    margin-top: 5px;
    padding-bottom: 5px;
    font-size: 16px;
    border-bottom: 1px solid rgba(0, 0, 0, 0.4);
    text-align: center;
  }

  .forgot-pass {
    margin-top: 15px;
    text-align: center;
    font-size: 12px;
    color: #cfcfcf;
  }

  .submit {
    margin-top: 40px;
    margin-bottom: 20px;
    background: #d4af7a;
    text-transform: uppercase;
  }
  span {
    color:white !important;
  }

  .fb-btn {
    border: 2px solid #d3dae9;
    color: #8fa1c7;
  }
  .fb-btn span {
    font-weight: bold;
    color: #455a81;
  }

  .sign-in {
    -webkit-transition-timing-function: ease-out;
    transition-timing-function: ease-out;
  }
  .cont.s--signup .sign-in {
    -webkit-transition-timing-function: ease-in-out;
    transition-timing-function: ease-in-out;
    -webkit-transition-duration: 1.2s;
    transition-duration: 1.2s;
    -webkit-transform: translate3d(640px, 0, 0);
    transform: translate3d(640px, 0, 0);
  }

  .sign-up {
    -webkit-transform: translate3d(-900px, 0, 0);
    transform: translate3d(-900px, 0, 0);
  }
  .cont.s--signup .sign-up {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }

  .icon-link {
    position: absolute;
    left: 5px;
    bottom: 5px;
    width: 32px;
  }
  .icon-link img {
    width: 100%;
    vertical-align: top;
  }
  .icon-link--twitter {
    left: auto;
    right: 5px;
  }

    input {
      border-bottom: 2px solid white !important;
    }

    select {
      color:black;
      width:100px;
    }

    button {
      margin-bottom: 70px !important;
      border-radius: .2em !important;
      text-transform: uppercase;
      transition: all 400ms ease-in-out;
    }

    button:hover {
      background: black !important;
      color:white;
    }

    .img {
      background: none !important;
    }





  @media only screen and (max-width: 1200px) {


  }


  @media only screen and (max-width: 900px) {

  }


  @media only screen and (max-width: 600px){
    form {
      margin: 0 !important;
      text-align: left !important;
    }

    label {
      margin: 0 !important;
      margin-left: 55px !important;
    }

    .btn-success {
      font-size:13px !important;
      background:rgb(51,51,51) !important;
      color:white !important;
      margin-top:50px !important;
    }

    select {
      background:white !important;
    }
    #story_title {
      margin: 0 !important;

    }
  }

  @media only screen and (max-width: 400px) {

  form {
    margin: 0 !important;
    text-align: left !important;
  }

    label {
      margin: 0 !important;
      margin-left: 25px !important;
    }

    .btn-success {
      font-size:13px !important;
      background:rgb(51,51,51) !important;
      color:white !important;
      margin-top:50px !important;
    }

    select {
      background:white !important;
    }
    #story_title {
      margin: 0 !important;

    }

  }

  @media only screen and (max-width: 350px) {
    form {
      margin: 0 !important;
      text-align: left !important;
    }

    label {
      margin: 0 !important;
      margin-left: 0px !important;
    }



    .btn-success {
      font-size:13px !important;
      background:rgb(51,51,51) !important;
      color:white !important;
      margin-top:50px !important;
    }

    select {
      background:white !important;
    }
    #story_title {
      margin: 0 !important;

    }
  }

</style>


<%= form_for @story, multipart:true do |form| %>
        <% if @story.errors.any? %>
            <div style="margin-top:100px;" id="error_explanation">
              <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

              <ul style="text-align: center;">
                <% @story.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>


<div style="margin-top:50px; height:100%;" class="cont">
  <div class="form sign-in">
    <label>
      <span>Title Of Story</span>
      <%= form.text_field :title , maxlength: 30 %>
    </label>
    <label>
      <span>Short Synopsis</span>
      <%= form.text_field :synopsis, maxlength:120 %>

    </label>
    <label>
      <span>Name Of Character 1 </span>
      <%= form.text_field :texter, maxlength: 15 %>
    </label>
    <label>
      <span>Name Of Character 2 </span>
      <%= form.text_field :reciever, maxlength: 15 %>
    </label>
    <label>
      <span> Optional Background Image </span>
      <%= form.file_field :image %>
    </label>
    <label>
      <span> Add A Cover Art  </span>
      <%= form.file_field :cover %>
    </label>
    <label>
      <span> Add A Category </span>
      <%= form.select :category_id , Category.all.collect { |c| [c.name, c.id]}, :prompt => "Select One" %>
    </label>
    <label>
      <%= form.button :submit , class: " btn-success ", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Creating Story Interface..."} %>
    </label>
  </div>
  <div style="background: none !important;" class="sub-cont">
    <div class="img">
      <div style="background: none !important;" class="img__text m--up">
        <h2>STORYMI</h2>
        <p>Let's Make Somethig Weird!</p>
      </div>
      <div class="img__text m--in">
        <h2>One of us?</h2>
        <p>If you already has an account, just sign in. We've missed you!</p>
      </div>

  </div>

    <% end %>

<%= render 'partials/footer' %>


<script>
    $("button").html("Start");
</script>

app/views/stories/category.html.erb
<%= @stories.each do |story| %>
  <%= story.title %>
<% end %>

app/views/stories/edit.html.erb
<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<% content_for :title, "TellAFiction - Revolutionizing Entertainment. Read, Watch, & Create Engaging Content" %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-infinitescroll/3.0.2/infinite-scroll.pkgd.js"></script>
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>

<style>

  body{
    overflow-x: hidden !important;
  }

  .grid {
    width:90%;
    margin: 0 auto !important;
    margin-top:50px !important;
    margin-bottom: 150px !important;
  }

  /* reveal grid after images loaded */
  .grid.are-images-unloaded {
    opacity: 0;
  }

  .grid__item,
  .grid__col-sizer {
    width: 32%;
  }

  .grid__gutter-sizer { width: 2%; }

  /* hide by default */
  .grid.are-images-unloaded .image-grid__item {
    opacity: 0;
  }

  .grid__item {
    margin-bottom: 20px;
    float: left;
  }

  .grid__item--height1 { height: 140px; background: #EA0; }
  .grid__item--height2 { height: 220px; background: #C25; }
  .grid__item--height3 { min-height: 300px; height:auto; background: rgb(51,51,51); }

  .grid__item--width2 { width: 66%; }

  .grid__item img {
    display: block;
    max-width: 100%;
  }


  .page-load-status {
    display: none; /* hidden by default */
    padding-top: 20px;
    border-top: 1px solid #DDD;
    text-align: center;
    color: #777;
  }

  .all-articles {
    text-align:center;
    font-size:50px;
    margin-top: 50px;
    margin-bottom: 50px;
    animation: show 400ms ease-in-out forwards;
  }

  @keyframes show {
    0%{
      transform: translateY(60px);
      opacity:0;
    }
    100%{
      transform: translateY(0px);
      opacity:1;
    }
  }

  .grid__item--height3 h1 {
    font-size:17px;
    margin-left:15px;
  }

  .grid__item--height3 img {
    width: 100%;
    height: auto;
  }

  .all-articles {
    color:white;
  }

  .grid__item--height3 a {
    color:white;
  }
  /* loader ellips in separate pen CSS */

    body {
      background:black;
      letter-spacing:1px;
      font-weight: 900 !important;
      font-size:12px;
      font-family: Helvetica, sans-serif;
    }

    .stories-link {
      border-bottom: 2px solid rgba(255,255,255,0.7);
    }



  @media only screen and (max-width: 1200px) {


  }


  @media only screen and (max-width: 900px) {

  }


  @media only screen and (max-width: 600px){
    .grid__item {
      width:100% !important;
    }
    .right-text {
      transform: translateY(10px)!important;

    }
  }

  @media only screen and (max-width: 400px) {

    .grid__item {
      width:100% !important;
    }

  }

  @media only screen and (max-width: 350px) {

  }

    .clickzer {
      cursor: pointer;
    }



</style>





<div class="grid are-images-unloaded">
  <div class="grid__col-sizer"></div>
  <div class="grid__gutter-sizer"></div>


  <% @stories.each do |article| %>

      <% if article.ispublished? %>
      <div class="grid__item grid__item--height3">
        <a href="/stories/<%= article.id %>/view">
          <img src="<%= article.cover.url(:medium) %>"/>
        </a>
        <% if !article.cover? %>
            <a href="/stories/<%= article.id %>/view">
              <h1 style="font-size:40px;"><%= article.title.truncate_words(6) %></h1>
            </a>
        <% else %>
            <a href="/stories/<%= article.id %>/view">

              <h1><%= article.title %></h1>
            </a>

            <h1 style="color:white;"><%= pluralize(article.impressionist_count, "view") %></h1>

            <h1 class="clickzer" onclick="window.location.href='/category/<%= article.category.id %>'"

                <% if article.category.name == "Romance" %>
            style="color:pink;"
                <% end %>
                <% if article.category.name == "Drama" %>
                style="color:darkcyan;"
                <% end %>
                <% if article.category.name == "Fantasy" %>
                style="color:mediumorchid;"
                <% end %>
                <% if article.category.name == "Thriller" %>
                style="color:red;"
                <% end %>
                <% if article.category.name == "Comedy" %>
                style="color:yellow;"
                <% end %>
                <% if article.category.name == "Mystery" %>
                style="color:darkolivegreen;"
                <% end %>
                <% if article.category.name == "SCI-FI" %>
                style="color:lightskyblue;"
                <% end %>
                <% if article.category.name == "Horror" %>
                style="color:darkred;"
                <% end %>

            ><%= article.category.name %></h1>


      <% end %>
        <a href="/profile/<%= article.user.id %>">
          <h1 class="parallax-scroll"><span>By <%= article.user.firstname %> <%= article.created_at.strftime('%B/%d/%Y') %></span></h1>
        </a>

      </div>
          <% end %>
  <% end %>





</div>

<div class="page-load-status">
  <div class="loader-ellips infinite-scroll-request">
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
    <span class="loader-ellips__dot"></span>
  </div>
  <p class="infinite-scroll-last">End of content</p>
  <p class="infinite-scroll-error">No more pages to load</p>
</div>

<%= render 'partials/footer' %>


<script>

  $(".footer-instructions").html("Hey <% if user_signed_in? %> <%= current_user.firstname %> <% end %> enjoy these amazing stories!");

  $(".layer").click(function(){
      window.location.href = "/users/sign_up";
  });

  $(".sign-up-message").hide();
  $(".fa-times-circle").click(function(){
     $(".sign-up-message").addClass("zoomOut");
  });

  $(window).load(function(){


      <% if !user_signed_in? %>
      setTimeout(function(){
          $(".d").trigger('play');
      },1300);
      <% end %>
      setTimeout(function(){
          $(".sign-up-message").show().addClass("pulse")
      },2000);

      $("body").css("overflow","auto");
      $(".loader").fadeOut("slow");
     $(".story-label-overlay").addClass("fadeInUp");
     $(".figuration").addClass("fadeInUp")

  });

</script>

<script>
    //
    //-------------------------------------//

    $(document).on("turbolinks:load")
    {
        // init Masonry
        $('.grid').masonry('reload');

        var $grid = $('.grid').masonry({
            itemSelector: 'none', // select none at first
            columnWidth: '.grid__col-sizer',
            gutter: '.grid__gutter-sizer',
            percentPosition: true,
            stagger: 30,
            // nicer reveal transition
            visibleStyle: {transform: 'translateY(0)', opacity: 1},
            hiddenStyle: {transform: 'translateY(100px)', opacity: 0},
        });

        // get Masonry instance
        var msnry = $grid.data('masonry');

        // initial items reveal
        $grid.imagesLoaded(function () {
            $grid.removeClass('are-images-unloaded');
            $grid.masonry('option', {itemSelector: '.grid__item'});
            var $items = $grid.find('.grid__item');
            $grid.masonry('appended', $items);
        });

        //-------------------------------------//
        // hack CodePen to load pens as pages

        var nextPenSlugs = [
            '202252c2f5f192688dada252913ccf13',
            'a308f05af22690139e9a2bc655bfe3ee',
            '6c9ff23039157ee37b3ab982245eef28',
        ];

        function getPenPath() {
            var slug = nextPenSlugs[this.loadCount];
            if (slug) {
                return 'modernfitness.herokuapp.com' + slug;
            }
        }
    }


    //-------------------------------------//
    // init Infinte Scroll





</script>


<%= will_paginate @stories %>

app/views/stories/new.html.erb
<% content_for :title, "New Story - TellAFiction" %>

<% if user_signed_in? %>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>





    <% else %>
      <script>
        window.location.href = "/"
      </script>
      <% end %>